### 기상데이터 파싱

In [1]:
# JSON 이용한 데이터 parsing
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup

In [5]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'

queryParams = '?' + \
              'ServiceKey=' + '7ul9l1k%2FJFfwA0srXtxquqh9%2BPWV5kkdA0szpIhfqffi%2FVi8XP710gIcFugKqywY4vf23Fem5KIaGx1HwbapRg%3D%3D'+ \
              '&pageNo='+ '1' + \
              '&numOfRows='+ '900' + \
              '&dataType='+ 'JSON' + \
              '&dataCd='+ 'ASOS' + \
              '&dateCd='+ 'HR' + \
              '&startDt='+ '20190101' + \
              '&startHh='+ '01' + \
              '&endDt='+ '20201231' + \
              '&endHh='+ '23' + \
              '&stnIds='+ '108'

result = requests.get(url + queryParams)
js = json.loads(result.content)

data = pd.DataFrame(js['response']['body']['items']['item'])

raw_data = ['tm','pa','ws','wd','ts','dc10Tca','rn'] #필요한 데이터 컬럼명 (일시, 기압, 풍속, 풍향, 온도, 전운량, 강수량)

In [4]:
raw_data_atmos = data.loc[:,raw_data]
raw_data_atmos

                  tm      pa   ws   wd    ts dc10Tca rn
0   2019-01-01 01:00  1024.0  1.8  270  -6.5       0
1   2019-01-01 02:00  1024.2  1.2  290  -7.1       0
2   2019-01-01 03:00  1024.3  2.2  270  -7.3       1
3   2019-01-01 04:00  1023.9  1.2  270  -7.5       3
4   2019-01-01 05:00  1023.6  2.1  270  -7.8       1
..               ...     ...  ...  ...   ...     ... ..
95  2019-01-05 00:00  1015.8  1.7  270  -2.1       9
96  2019-01-05 01:00  1016.1  2.2  320  -2.5       0
97  2019-01-05 02:00  1016.5  3.0  290  -2.8       8
98  2019-01-05 03:00  1016.6  2.1  320  -3.5       0
99  2019-01-05 04:00  1016.2  1.4  360  -4.4       0

[100 rows x 7 columns]